# Generated by Django 3.2.12 on 2022-10-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbnuevocodigocatastral',
            name='canton',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbnuevocodigocatastral',
            name='conexion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbnuevocodigocatastral',
            name='manzana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbnuevocodigocatastral',
            name='parroquia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbnuevocodigocatastral',
            name='predio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbnuevocodigocatastral',
            name='provincia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbnuevocodigocatastral',
            name='sector',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbnuevocodigocatastral',
            name='zona',
            field=models.IntegerField(),
        ),
    ]
