# Generated by Django 3.2.12 on 2022-10-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0002_auto_20221003_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbdatosinmueble',
            name='unidades_uso',
        ),
        migrations.AddField(
            model_name='tbdatosinmueble',
            name='unidades_comercial',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosinmueble',
            name='unidades_domestico',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosinmueble',
            name='unidades_industrial',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosinmueble',
            name='unidades_publico',
            field=models.IntegerField(null=True),
        ),
    ]
