# Generated by Django 3.2.12 on 2022-10-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0003_auto_20221005_0518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbUnidadesUso',
        ),
    ]
