# Generated by Django 3.2.12 on 2022-10-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0004_delete_tbunidadesuso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbdatosgeneralesusuario',
            old_name='apellidos',
            new_name='nombres_apellidos',
        ),
        migrations.RemoveField(
            model_name='tbdatosgeneralesusuario',
            name='nombres',
        ),
    ]
