# Generated by Django 3.2.12 on 2022-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0006_auto_20221005_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbdatosconexionalcantarillado',
            name='caracteristica_conexion',
        ),
        migrations.RemoveField(
            model_name='tbdatosmedidor',
            name='estado_medidor',
        ),
        migrations.AddField(
            model_name='tbdatosconexionalcantarillado',
            name='con_caja',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosconexionalcantarillado',
            name='sin_caja_conexion_directa',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosconexionalcantarillado',
            name='sin_conexion',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosconexionalcantarillado',
            name='tiene_caja_aall',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosmedidor',
            name='luna_opaca',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosmedidor',
            name='luna_rota',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosmedidor',
            name='malogrado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosmedidor',
            name='operativo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tbdatosmedidor',
            name='sin_tapa',
            field=models.BooleanField(null=True),
        ),
    ]
