# Generated by Django 3.2.12 on 2022-10-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0007_auto_20221005_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbCaracteristicasConexionAlc',
        ),
    ]
