# Generated by Django 3.2.12 on 2022-10-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0008_delete_tbcaracteristicasconexionalc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbEstadoMedidor',
        ),
    ]
