# Generated by Django 3.2.12 on 2022-10-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0009_delete_tbestadomedidor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbdatosconexionalcantarillado',
            old_name='con_caja',
            new_name='con_caja_con_medidor',
        ),
        migrations.RenameField(
            model_name='tbdatosconexionalcantarillado',
            old_name='tiene_caja_aall',
            new_name='con_caja_sin_medidor',
        ),
    ]
