# Generated by Django 3.2.12 on 2022-11-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0011_auto_20221028_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbfichatecnica',
            name='nuevo_codigo_catastral',
        ),
        migrations.AddField(
            model_name='tbnuevocodigocatastral',
            name='fichatecnica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbfichatecnica'),
        ),
    ]
