# Generated by Django 3.2.16 on 2022-11-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0011_auto_20221106_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbfichatecnica',
            old_name='responsable_predio_id',
            new_name='responsable_predio',
        ),
    ]
