# Generated by Django 3.2.12 on 2022-11-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0012_auto_20221108_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdatosgeneralesusuario',
            name='cedula_identidad',
            field=models.CharField(max_length=13),
        ),
    ]
