# Generated by Django 3.2.15 on 2022-11-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0012_rename_responsable_predio_id_tbfichatecnica_responsable_predio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbnuevocodigocatastral',
            name='conexion',
            field=models.IntegerField(blank=True),
        ),
    ]
