# Generated by Django 3.2.15 on 2022-11-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0014_auto_20221108_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_codo',
            field=models.IntegerField(choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_directo',
            field=models.IntegerField(choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_llave_paso',
            field=models.IntegerField(choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_niple_estandar',
            field=models.IntegerField(choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_tubo_entrada',
            field=models.IntegerField(choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_tubo_salida',
            field=models.IntegerField(choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
    ]
