# Generated by Django 3.2.15 on 2022-11-09 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0015_auto_20221108_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdatoscajaregistrodesague',
            name='estado_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbestadocajard'),
        ),
        migrations.AlterField(
            model_name='tbdatoscajaregistrodesague',
            name='material_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbmaterialcajard'),
        ),
        migrations.AlterField(
            model_name='tbdatoscajaregistrodesague',
            name='ubicacion_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbubicacioncajard'),
        ),
        migrations.AlterField(
            model_name='tbdatoscomplementarios',
            name='jardin_huerto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbjardinhuerto'),
        ),
        migrations.AlterField(
            model_name='tbdatoscomplementarios',
            name='pavimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbpavimento'),
        ),
        migrations.AlterField(
            model_name='tbdatoscomplementarios',
            name='tipo_vereda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbtipovereda'),
        ),
        migrations.AlterField(
            model_name='tbdatosconexionalcantarillado',
            name='diametro_conexion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbdiametroconexionalc'),
        ),
        migrations.AlterField(
            model_name='tbdatosconexionalcantarillado',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosconexionalcantarillado',
            name='material_conexion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbmaterialconexionalc'),
        ),
        migrations.AlterField(
            model_name='tbdatosconexionalcantarillado',
            name='situacion_conexion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbsituacionconexionalc'),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='diametro_medidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbdiametromedidor'),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_codo',
            field=models.IntegerField(blank=True, choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_directo',
            field=models.IntegerField(blank=True, choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_llave_paso',
            field=models.IntegerField(blank=True, choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_niple_estandar',
            field=models.IntegerField(blank=True, choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_tubo_entrada',
            field=models.IntegerField(blank=True, choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='estado_tubo_salida',
            field=models.IntegerField(blank=True, choices=[[0, 'Bueno'], [1, 'Malo']], null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='lectura',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='marca_medidor',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosmedidor',
            name='numero_medidor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbdatossinconexionaguaalcantarillado',
            name='abastecimiento_agua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbabastecimientoaguapotable'),
        ),
        migrations.AlterField(
            model_name='tbdatossinconexionaguaalcantarillado',
            name='almacenamiento_agua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbalmacenamientoaguapotable'),
        ),
        migrations.AlterField(
            model_name='tbdatossinconexionaguaalcantarillado',
            name='numero_horas_abastecimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbdatossinconexionaguaalcantarillado',
            name='saneamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbsaneamiento'),
        ),
        migrations.AlterField(
            model_name='tbdatostapacajaalcantarillado',
            name='estado_tapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbestadotapa'),
        ),
        migrations.AlterField(
            model_name='tbdatostapacajaalcantarillado',
            name='material_tapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbmaterialtapa'),
        ),
        migrations.AlterField(
            model_name='tbfichatecnica',
            name='fecha_encuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbfichatecnica',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbfichatecnica',
            name='tercera_edad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbfichatecnica',
            name='tiene_carne_conadis',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbrecoleccionbasura',
            name='especifique_numero_cuadras',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
