# Generated by Django 3.2.15 on 2022-11-12 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0016_auto_20221108_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdatosconexionaguapotable',
            name='caracteristicas_conexion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbcaracteristicasconexion'),
        ),
    ]
