# Generated by Django 3.2.12 on 2022-11-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0016_tbdatosresponsableacometida'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbdatosgeneralesusuario',
            name='cedula_identidad',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='tbdatosgeneralesusuario',
            name='nombres_apellidos',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
