# Generated by Django 3.2.12 on 2022-11-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0017_auto_20221108_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbdatosgeneralesusuario',
            name='cedula_identidad',
        ),
        migrations.RemoveField(
            model_name='tbdatosgeneralesusuario',
            name='nombres_apellidos',
        ),
    ]
