# Generated by Django 3.2.12 on 2022-11-09 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0019_auto_20221109_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbdatosresponsableacometida',
            name='nuevocodigocatastral',
        ),
        migrations.AddField(
            model_name='tbnuevocodigocatastral',
            name='responsableacometida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbdatosresponsableacometida'),
        ),
    ]
