# Generated by Django 3.2.12 on 2022-11-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0020_auto_20221109_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbdatoscajaagua',
            name='fichatecnica',
        ),
        migrations.RemoveField(
            model_name='tbdatosconexionaguapotable',
            name='fichatecnica',
        ),
        migrations.RemoveField(
            model_name='tbdatosmarcotapacajaagua',
            name='fichatecnica',
        ),
        migrations.RemoveField(
            model_name='tbdatosmedidor',
            name='fichatecnica',
        ),
        migrations.AddField(
            model_name='tbnuevocodigocatastral',
            name='datos_caja_agua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbdatoscajaagua'),
        ),
        migrations.AddField(
            model_name='tbnuevocodigocatastral',
            name='datos_conexion_agua_potable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbdatosconexionaguapotable'),
        ),
        migrations.AddField(
            model_name='tbnuevocodigocatastral',
            name='datos_marco_tapa_caja_agua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbdatosmarcotapacajaagua'),
        ),
        migrations.AddField(
            model_name='tbnuevocodigocatastral',
            name='datos_medidor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbdatosmedidor'),
        ),
    ]
