# Generated by Django 3.2.12 on 2022-11-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0021_auto_20221109_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbnuevocodigocatastral',
            old_name='datos_medidor_id',
            new_name='datos_medidor',
        ),
    ]
