# Generated by Django 3.2.12 on 2022-11-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0022_rename_datos_medidor_id_tbnuevocodigocatastral_datos_medidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbEstadoAcometidaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_acometida_agua', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TbEstadoAcometidaAlcantarillado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_acometida_alcantarillado', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='tbfichatecnica',
            name='estado_acometida_alcantarillado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbestadoacometidaalcantarillado'),
        ),
        migrations.AddField(
            model_name='tbnuevocodigocatastral',
            name='estado_acometida_agua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbestadoacometidaagua'),
        ),
    ]
