# Generated by Django 3.2.12 on 2022-11-14 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0017_alter_tbdatosconexionaguapotable_caracteristicas_conexion'),
        ('datasheet', '0023_auto_20221110_2337'),
    ]

    operations = [
    ]
