# Generated by Django 3.2.12 on 2022-11-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0024_merge_20221113_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdatoscajaagua',
            name='estado_caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbestadocaja'),
        ),
        migrations.AlterField(
            model_name='tbdatoscajaagua',
            name='material_caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbmaterialcaja'),
        ),
        migrations.AlterField(
            model_name='tbdatoscajaagua',
            name='ubicacion_caja_agua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbubicacioncajagua'),
        ),
        migrations.AlterField(
            model_name='tbdatosconexionaguapotable',
            name='caracteristicas_conexion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbcaracteristicasconexion'),
        ),
        migrations.AlterField(
            model_name='tbdatosconexionaguapotable',
            name='diametro_conexion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbdiametroconexion'),
        ),
        migrations.AlterField(
            model_name='tbdatosconexionaguapotable',
            name='fecha_instalacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tbdatosconexionaguapotable',
            name='material_conexion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbmaterialconexion'),
        ),
        migrations.AlterField(
            model_name='tbdatosconexionaguapotable',
            name='situacion_conexion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbsituacionconexion'),
        ),
        migrations.AlterField(
            model_name='tbdatosmarcotapacajaagua',
            name='estado_marco_tapa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbestadomarcotapa'),
        ),
        migrations.AlterField(
            model_name='tbdatosmarcotapacajaagua',
            name='material_marco_tapa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbmaterialmarcotapa'),
        ),
        migrations.AlterField(
            model_name='tbfichatecnica',
            name='responsable_predio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasheet.tbresponsablepredio'),
        ),
    ]
