title_ficha_catastral = "FICHA CATASTRAL USUARIOS DE AGUA POTABLE, ALCANTARILLADO Y RECOLECCIÓN DE BASURA"
title_coordinacion_agua = "COORDINACIÓN DE AGUA"
title_nueva_acometida = "NUEVA ACOMETIDA"
title_coordinacion_desechos_solidos = "COORDINACIÓN DE DESECHOS SÓLIDOS"
title_coordinacion_alcantarillado = "COORDINACIÓN ALCANTARILLADO"
